from __future__ import annotations

from typing import Final

# Fixed column order for ``work/catalog/clips.parquet``.
CLIPS_COLUMNS: Final[list[str]] = [
    "clip_id",
    "source_release",
    "normalized_relative_source_path",
    "source_row_index",
    "audio_sha256",
    "text_raw",
    "text_norm",
    "speaker_id",
    "sentence_id",
    "disposition",
    "reject_reason",
    "duration_sec",
    "quality_score",
    "estimated_snr_db",
    "silence_ratio",
    "phonemes",
    "feature_source",
    "biphones",
    "triphones",
    "moras",
    "fullcontext_labels",
    "analysis_warnings",
    "pipeline_hash",
    "audio_cache_rel_path",
    "split",
    "duplicate_group_ids",
    "selection_rank",
    "selection_utility",
    "override_flags",
    "analyzed_at",
]

CLIPS_SCHEMA: Final[dict[str, str]] = {
    "clip_id": "string",
    "source_release": "string",
    "normalized_relative_source_path": "string",
    "source_row_index": "int64",
    "audio_sha256": "string",
    "text_raw": "string",
    "text_norm": "string",
    "speaker_id": "string",
    "sentence_id": "string",
    "disposition": "string",
    "reject_reason": "string",
    "duration_sec": "float64",
    "quality_score": "float64",
    "estimated_snr_db": "float64",
    "silence_ratio": "float64",
    "phonemes": "string",
    "feature_source": "string",
    "biphones": "list[string]",
    "triphones": "list[string]",
    "moras": "list[string]",
    "fullcontext_labels": "list[string]",
    "analysis_warnings": "list[string]",
    "pipeline_hash": "string",
    "audio_cache_rel_path": "string",
    "split": "string",
    "duplicate_group_ids": "string",
    "selection_rank": "int64",
    "selection_utility": "float64",
    "override_flags": "string",
    "analyzed_at": "string",
}
